### ISSUE TITLE
Not able to import into Angular project

### ISSUE THREAD

**Issue by kokhongmooi** [sisimomo/Spring-Filter-Query-Builder#1]
Not able to import to Angular project. Please help.

**Comment by dst3p** [comment]
@kokhongmooi did you figure this out?

**Comment by kokhongmooi** [comment]
yes, but it would be great if we have the @types file for Angular developers.

**Comment by torshid** [comment]
Hello @kokhongmooi @dst3p 
It would be great if you can open a PR, I didn't play with Angular since a long time, @sisimomo may also help.
