### ISSUE TITLE
SpringFilterQueryBuilder can not be exported anymore

### ISSUE THREAD

**Issue by mfocuz** [sisimomo/Spring-Filter-Query-Builder#13]
Hi,

Sorry in advance, I'm not really expert in UI. I used this construction before

`import { SpringFilterQueryBuilder as builder } from 'spring-filter-query-builder';`

and I've got error
`export 'SpringFilterQueryBuilder' (imported as 'builder') was not found in 'spring-filter-query-builder' (possible exports: Comparator, Function, Operator, sfAbs, sfAnd, sfAvg, sfCeiling, sfConcat, sfCount, sfCountDistinct, sfCurrentDate, sfCurrentTime, sfCurrentTimestamp, sfCustomFunction, sfEqual, sfExists, sfGe, sfGt, sfIn, sfIsEmpty, sfIsNotEmpty, sfIsNotNull, sfIsNull, sfLe, sfLength, sfLike, sfLower, sfLt, sfMax, sfMin, sfNot, sfNotEqual, sfNotIn, sfOr, sfSize, sfSum, sfTrim, sfUpper)`

Could you advise how to adjust code using previous versions of your lib to make it work on new version of lib?

**Comment by sisimomo** [comment]
Starting from version 1.x.x, there have been significant changes. Instead of importing a class and calling static methods on it (like we did in 0.x.x), you now directly import needed functions.

As a result, the updated method for utilizing the library is as shown below:

```js
import { sfAnd, sfEqual, sfGt } from 'spring-filter-query-builder';

let filter = sfAnd([sfEqual('status', 'active'), sfGt('createdAt', '1-1-2000')]);
console.log(filter.toString());
```

**Comment by mfocuz** [comment]
filter.toString returns this

`function () {
        return '(' + this.items.map(function (item) { return item.toString(); }).join(" " + this.operatorKeyWord + " ") + ')';
}`

**Comment by mfocuz** [comment]
I replaced all calls with new function methods,
`if (filters_array.length) {
        console.log("filters_array.length=" + filters_array.length);
        search = sfAnd(...filters_array);
        console.log("search=" + search.toString());
}`

For some reason I got this exception

`Uncaught (in promise) TypeError: this.items.map is not a function
    toString operators.js:22
    fetchData programsStore.js:43`
