### ISSUE TITLE
like query not working

### ISSUE THREAD

**Issue by jhswedeveloper** [sisimomo/Spring-Filter-Query-Builder#4]
When adding a like query 

```js
builder.and(builder.like('waybillNumber', `${wayBillNumber}%`))
```

will produce 
filter=(waybillNumber%20~%20%2712%%27)

but it needs to url-encode the % 

expected should be
filter=waybillNumber%20~%20%2712%25%27

**Comment by svallieres-re** [comment]
The library only generates a string using the builder. If you send the generated string in a get parameter, it is your responsibility to encode the parameter.

**Comment by sisimomo** [comment]
The library only generates a string using the builder. If you send the generated string in a get parameter, it is your responsibility to encode the parameter.
