### ISSUE TITLE
Operator "Not" does not work correctly

### ISSUE THREAD

**Issue by UmNiK7** [sisimomo/Spring-Filter-Query-Builder#6]
Operator "Not" does not work correctly

Example:
SFQB.not(SFQB.like("test", "value")).toString()

Actual result - (test ~ 'value')
Expected result - (NOT (test ~ 'value'))

**Comment by sisimomo** [comment]
You are right, thanks for reporting it! I'll settle this. But now that I have some experience with Typescript, I will rewrite the library with Typescript, set up unit tests and set up a GitHub pipeline for continuous deployment.

In a few days, I should be done.

Sorry for the inconvenience
