### ISSUE TITLE
Exports does not work corretctly

### ISSUE THREAD

**Issue by UmNiK7** [sisimomo/Spring-Filter-Query-Builder#8]
<img width="1330" alt="image" src="https://github.com/sisimomo/Spring-Filter-Query-Builder/assets/52335499/76b5f038-937c-4585-bdd4-101f6224f3da">

Exports does not work corretctly

**Comment by sisimomo** [comment]
Could you check your local copy.

At first glance, the newly uploaded npm version (1.0.0) of the [`dist/cjs/index.js`](https://www.npmjs.com/package/spring-filter-query-builder?activeTab=code) file does not match yours.

**Comment by sisimomo** [comment]
Here is a working sandbox that seems to work with the latest NPM version of the package.

https://codesandbox.io/s/npm-playground-forked-yp3mgd?file=/src/styles.css

Could you duplicate your problem in an online sandbox, please.

**Comment by UmNiK7** [comment]
IDE (JetBrains) does not see methods, but it work fine
