### ISSUE TITLE
Fix brackets

### ISSUE THREAD

**Issue by UmNiK7** [sisimomo/Spring-Filter-Query-Builder#9]
src/comparators.ts:112
src/comparators.ts:124

Fix brackets please
Round brackets instead of square brackets  
 "[ -> ("
 "] -> )"

**Comment by torshid** [comment]
Spring Filter 3.x.x uses brackets (arrays) with `in` instead of parentheses. You may consider changing your version or maybe extend the typescript code and add your own comparator?

What do you think @sisimomo?

**Comment by sisimomo** [comment]
I think the library should only support the syntax supported by Spring Filter latest version (a version compatibility table would be nice). Any other need should be taken care of by the user.

Currently the library classes can't be extended, I'll look into that as soon as I have some time.

I think all library classes should be user extendable. This should be pretty easy, but I'll have to create some unit tests and examples before releasing this feature.
